{{- if .Values.opentelemetryCollector.enabled }}
{{- if (include "imagePullSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: {{ .Values.opentelemetryCollector.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}
